### ISSUE TITLE
MQTT : Loosing status after long time

### ISSUE THREAD

**Issue by cbijon** [Domochip/Wireless-Fils-Pilotes#1]
Bonjour,

J'essaye de configurer les modules pour communiquer en MQTT avec homeassistant. Au démarrage, les modules s'inscrivent bien sur le broker. Cependant après un long moment sans échanges, genre après le passage de l'été, les Topic disparaissent et donc homeassistant perds les appareils.

Et cela est ennuyeux car homeassistant pense qu'ils ne sont plus là et je ne peux donc plus récupérer les statuts en cours.

Pourriez-vous modifier pour faire en sorte que les modules envoi en permanence leur état toutes les 30 secondes ? Et rendre le topic permanent ?

Codialement,

**Comment by Domochip** [comment]
Bonjour,

je ne connais pas le fonctionnement de homeassistant, mais cela parait étrange qu'il "oublie" un équipement, non?

**Comment by cbijon** [comment]
Bonjour,

Entre temps, je me suis amusé à refaire une autre intégration via ESPHome et l'inscription dans homeassistant est encore plus simple. https://github.com/cbijon/ESPHOME-DOMOCHIP-WFP1

**Comment by Domochip** [comment]
Ah oui, c'est vrai!
Bonne Journée
